### ISSUE TITLE
Wrong Account Type User - Say F2p Ult

### ISSUE THREAD

**Issue by puremana** [vmeow/f2pehp#20]
Say F2p Ult is in ultimate ironman, not a regular account.

https://www.f2p.wiki/players/Say%20F2p%20Ult

![image](https://user-images.githubusercontent.com/2869411/68148298-8e5fbd00-ffa0-11e9-9bcf-25c9e9cf45fb.png)
![image](https://user-images.githubusercontent.com/2869411/68148301-90298080-ffa0-11e9-83a3-9bd0aee928cf.png)

I'm not sure if clicking the `wrong account type? click here` actually did anything. If it did notify you already, perhaps when clicked a message could be displayed saying your request for the check had been sent successfully.

Thanks!

**Comment by vmeow** [comment]
Thanks for documenting this and apologies for the delay. The root issue has been fixed as part of PRs #19, which was due to some unexpected Jagex API issues and some improvements we made to API calls.

#22 also further improved the `wrong_account_type?` to correctly import the same gains/records into the new account type.
