### ISSUE TITLE
Current Top list showing inaccurate XP gained

### ISSUE THREAD

**Issue by creibsome** [vmeow/f2pehp#32]
Current Top list showing inconsistent xp gain (0 even though ehp gain is shown). Correct xp gain is displayed in the user detail gains page.

![Screenshot_20200115-122727_Brave](https://user-images.githubusercontent.com/45184802/72456628-0f061b00-3793-11ea-8c57-35b405e426c2.jpg)

**Comment by vmeow** [comment]
Not sure what's going on here, but it's probably related to recent official hiscores downtime. I wager it's a data issue and not a code issue, but who knows. Also due to my slowness, I'm unable to see this since current top is time-sensitive.

Closing for now; but feel free to re-open if it occurs again, and I'll try to be more responsive.
